In [ ]:
#import libraries
import numpy as np 
import pandas as pd

In [ ]:
#loading excel file
df = pd.read_excel("sales_dataset.xlsx")

print("Dataset loaded successfully!")
print("Shape:", df.shape)

In [3]:
#making a copy of the original dataset
raw_df = df.copy()

In [4]:
#standardize column names
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
)

print(df.columns.tolist())

['order_id', 'date', 'status', 'fulfilment', 'sales_channel', 'ship_service_level', 'style', 'sku', 'category', 'size', 'asin', 'courier_status', 'qty', 'currency', 'amount', 'ship_city', 'ship_state', 'ship_postal_code', 'ship_country', 'promotion_ids', 'b2b', 'fulfilled_by', 'unnamed:_22']

In [5]:
#Check dataset information
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.info()

Rows: 128949
Columns: 23
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128949 entries, 0 to 128948
Data columns (total 23 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   order_id            128949 non-null  object
 1   date                128949 non-null  datetime64[ns]
 2   status              128949 non-null  object
 3   fulfilment          128949 non-null  object
 4   sales_channel       128949 non-null  object
 5   ship_service_level  128949 non-null  object
 6   style               128949 non-null  object
 7   sku                 128949 non-null  object
 8   category            128949 non-null  object
 9   size                128949 non-null  object
 10  asin                128949 non-null  object
 11  courier_status      122078 non-null  object
 12  qty                 128949 non-null  int64
 13  currency            121155 non-null  object
 14  amount              121155 non-null  float64
 15  ship_city           128916 non-null  object
 16  ship_state          128916 non-null  object
 17  ship_postal_code    128916 non-null  float64
 18  ship_country        128916 non-null  object
 19  promotion_ids       79807 non-null   object
 20  b2b                 128949 non-null  bool
 21  fulfilled_by        39270 non-null   object
 22  unnamed:_22         79908 non-null   float64
dtypes: bool(1), datetime64[ns](1), float64(3), int64(1), object(17)
memory usage: 21.8+ MB

In [6]:
#Check duplicate rows
duplicate_count = df.duplicated().sum()

print("Exact duplicate rows:", duplicate_count)

Exact duplicate rows: 6

In [7]:
#drop duplicate
df = df.drop_duplicates()

print("Shape after removing exact duplicates:", df.shape)

Shape after removing exact duplicates: (128943, 23)

In [8]:
#repeated and duplicate orders 
duplicate_order_ids = df["order_id"].duplicated().sum()

print("Repeated Order ID rows:", duplicate_order_ids)
print("Unique Orders:", df["order_id"].nunique())

Repeated Order ID rows: 8591
Unique Orders: 120352

In [9]:
#droping unnessary columns 
columns_to_drop = [
    "unnamed:_22",
    "currency",
    "ship_country",
    "fulfilled_by"
]

df = df.drop(
    columns=columns_to_drop,
    errors="ignore"
)

print("Columns after removal:")
print(df.columns.tolist())

Columns after removal:
['order_id', 'date', 'status', 'fulfilment', 'sales_channel', 'ship_service_level', 'style', 'sku', 'category', 'size', 'asin', 'courier_status', 'qty', 'amount', 'ship_city', 'ship_state', 'ship_postal_code', 'promotion_ids', 'b2b']

In [10]:
# first 10 rows
df.head(10)

,order_id,date,status,fulfilment,sales_channel,ship_service_level,style,sku,category,size,asin,courier_status,qty,amount,ship_city,ship_state,ship_postal_code,promotion_ids,b2b
0,171-7326790-9044369,2022-03-31,Shipped,Amazon,Amazon.in,Expedited,JNE3614,JNE3614-KR-L,kurta,L,B098133PV7,Shipped,1,453.00,ARANI TIRUVANNAMALAI DISTRICT,TAMIL NADU,632317.0,IN Core Free Shipping 2015/04/08 23-48-5-108,False
1,171-7326790-9044369,2022-03-31,Shipped,Amazon,Amazon.in,Expedited,JNE3294,JNE3294-KR-L,kurta,L,B07R5WM5YR,Shipped,1,353.00,ARANI TIRUVANNAMALAI DISTRICT,TAMIL NADU,632317.0,IN Core Free Shipping 2015/04/08 23-48-5-108,False
2,171-7192082-3049169,2022-03-31,Cancelled,Merchant,Amazon.in,Standard,JNE3461,JNE3461-KR-L,kurta,L,B08B3YWTLK,NaN,0,360.95,ARANI TIRUVANNAMALAI DISTRICT,TAMIL NADU,632317.0,NaN,False
3,402-9467302-4929937,2022-03-31,Shipped,Amazon,Amazon.in,Expedited,JNE3405,JNE3405-KR-XXXL,kurta,3XL,B081WZ4T3V,Shipped,1,449.00,PANCHKULA,HARYANA,134116.0,NaN,False
4,405-1392423-9557138,2022-03-31,Shipped,Amazon,Amazon.in,Expedited,JNE3068,JNE3068-KR-A-L,kurta,L,B07H7D7NJZ,Shipped,1,688.00,Tirupati,ANDHRA PRADESH,517501.0,IN Core Free Shipping 2015/04/08 23-48-5-108,False
5,407-7904992-8992306,2022-03-31,Shipped,Amazon,Amazon.in,Expedited,J0281,J0281-SKD-L,Set,L,B08QGMNRBT,Shipped,1,1496.00,JAGALUR,KARNATAKA,577528.0,IN Core Free Shipping 2015/04/08 23-48-5-108,False
6,407-1987486-1549956,2022-03-31,Shipped,Amazon,Amazon.in,Expedited,SET268,SET268-KR-NP-XL,Set,XL,B08XQBF1G4,Shipped,1,698.00,GURUGRAM,HARYANA,122018.0,IN Core Free Shipping 2015/04/08 23-48-5-108,False
7,408-8834155-2110755,2022-03-31,Shipped,Amazon,Amazon.in,Expedited,J0126,J0126-SKD-M,Set,M,B08V1R5MMB,Shipped,1,849.00,Bangalore,KARNATAKA,560097.0,IN Core Free Shipping 2015/04/08 23-48-5-108,False
8,408-8834155-2110755,2022-03-31,Shipped,Amazon,Amazon.in,Expedited,SET227,SET227-KR-PP-A-M,Set,M,B08P1GQV6V,Shipped,1,566.00,Bangalore,KARNATAKA,560097.0,IN Core Free Shipping 2015/04/08 23-48-5-108,False
9,403-9181934-8229136,2022-03-31,Shipped,Amazon,Amazon.in,Expedited,JNE3504,JNE3504-KR-L,kurta,L,B097ZZNTK2,Shipped,1,481.00,BENGALURU,KARNATAKA,560061.0,NaN,False

In [11]:
#Remove unnecessary spaces
text_columns = df.select_dtypes(include="object").columns

for col in text_columns:
    df[col] = df[col].str.strip()

In [12]:
#converting text to lowercase
text_columns = df.select_dtypes(include="object").columns

for col in text_columns:
    df[col] = df[col].str.lower()

In [13]:
#Clean city names
city_mapping = {
    "bengalore": "bangalore",
    "banglore": "bangalore",
    "bengaluru": "bangalore",
    "new delhi": "new delhi",
    "delhi": "delhi"
}

df["ship_city"] = df["ship_city"].replace(city_mapping)

In [14]:
print(df["ship_city"].value_counts().head(20))

ship_city
bangalore        13272
hyderabad         9122
mumbai            7120
new delhi         6337
chennai           6282
pune              4615
kolkata           2844
gurugram          1953
thane             1877
lucknow           1627
noida             1627
ghaziabad         1484
ahmedabad         1444
navi mumbai       1403
jaipur            1061
coimbatore         891
visakhapatnam      858
faridabad          820
patna              816
bhubaneswar        779
Name: count, dtype: int64

In [15]:
#cleaning state names
state_mapping = {
    "bihar": "bihar",
    "bhihar": "bihar",

    "orissa": "odisha",
    "orissa ": "odisha",

    "rajsthan": "rajasthan",
    "rajshthan": "rajasthan",

    "rj": "rajasthan",

    "pb": "punjab",

    "mp": "madhya pradesh",

    "up": "uttar pradesh",

    "uk": "uttarakhand",

    "tn": "tamil nadu",

    "ka": "karnataka",

    "kl": "kerala",

    "ap": "andhra pradesh",

    "ts": "telangana",

    "wb": "west bengal",

    "mh": "maharashtra",

    "gj": "gujarat",

    "hr": "haryana",

    "dl": "delhi",
     "nl": "nagaland",
    "ar": "arunachal pradesh",
    "punjab/mohali/zirakpur": "punjab",
    "pondicherry": "puducherry"
}

df["ship_state"] = df["ship_state"].replace(state_mapping)

In [16]:
print(df["ship_state"].value_counts())

ship_state
maharashtra          22256
karnataka            17320
tamil nadu           11481
telangana            11327
uttar pradesh        10635
delhi                 6964
kerala                6584
west bengal           5961
andhra pradesh        5429
gujarat               4489
haryana               4413
rajasthan             2717
madhya pradesh        2529
odisha                2138
bihar                 2114
punjab                1917
assam                 1663
uttarakhand           1552
jharkhand             1456
goa                   1137
chhattisgarh           909
himachal pradesh       788
jammu & kashmir        702
puducherry             351
chandigarh             333
manipur                316
andaman & nicobar      257
meghalaya              207
sikkim                 205
nagaland               187
tripura                151
arunachal pradesh      147
new delhi               81
mizoram                 76
dadra and nagar         70
ladakh                  43
lakshadweep              4
apo                      1
Name: count, dtype: int64

In [17]:
df = df[df["ship_state"] != "apo"]

In [18]:
for col in df.select_dtypes(include="object").columns:
    df[col] = (
        df[col]
        .str.replace(r"\s+", " ", regex=True)
        .str.strip()
    )

In [19]:
print("Rows after removing apo:", len(df))
print(df["ship_state"].value_counts().tail(10))

Rows after removing apo: 128942
ship_state
meghalaya            207
sikkim               205
nagaland             187
tripura              151
arunachal pradesh    147
new delhi             81
mizoram               76
dadra and nagar       70
ladakh                43
lakshadweep            4
Name: count, dtype: int64

In [40]:
#date
df["date"] = pd.to_datetime(
    df["date"],
    errors="coerce",
    dayfirst=True
)

In [41]:
print(df["date"].dtype)

datetime64[ns]

In [42]:
#Convert numerical columns
df["qty"] = pd.to_numeric(
    df["qty"],
    errors="coerce"
)

df["amount"] = pd.to_numeric(
    df["amount"],
    errors="coerce"
)

In [43]:
print(df[["qty", "amount"]].dtypes)

qty         int64
amount    float64
dtype: object

In [44]:
#checking missing values
missing = df.isnull().sum()

print(missing[missing > 0])

amount    7790
dtype: int64

In [45]:
missing_report = pd.DataFrame({
    "missing_count": df.isnull().sum(),
    "missing_percentage": (
        df.isnull().sum() / len(df) * 100
    ).round(2)
})

missing_report = missing_report[
    missing_report["missing_count"] > 0
].sort_values(
    "missing_percentage",
    ascending=False
)

print(missing_report)

        missing_count  missing_percentage
amount           7790                6.04

In [46]:
#Handle missing categorical values
categorical_columns = [
    "status",
    "fulfilment",
    "sales_channel",
    "ship_service_level",
    "category",
    "size",
    "courier_status",
    "ship_city",
    "ship_state",
    "promotion_ids",
    "b2b"
]

for col in categorical_columns:
    if col in df.columns:
        df[col] = df[col].fillna("unknown")

In [47]:
#handling missing postal code
df["ship_postal_code"] = (
    pd.to_numeric(
        df["ship_postal_code"],
        errors="coerce"
    )
    .astype("Int64")
    .astype("string")
)

In [48]:
df["ship_postal_code"] = df["ship_postal_code"].fillna("unknown")

In [49]:
#Check impossible values(negative ammount and quantaties)
print(
    "Negative quantities:",
    (df["qty"] < 0).sum()
)
print(
    "Negative amounts:",
    (df["amount"] < 0).sum()
)
print(
    "Zero quantity rows:",
    (df["qty"] == 0).sum()
)
print(
    "Missing/invalid dates:",
    df["date"].isna().sum()
)

Negative quantities: 0
Negative amounts: 0
Zero quantity rows: 12806
Missing/invalid dates: 0

In [50]:
print("Status:")
print(df["status"].unique())

print("\nFulfilment:")
print(df["fulfilment"].unique())

print("\nCategory:")
print(df["category"].unique())

print("\nSales Channel:")
print(df["sales_channel"].unique())

print("\nShip Service Level:")
print(df["ship_service_level"].unique())

Status:
['shipped' 'cancelled' 'shipped - delivered to buyer'
 'shipped - returned to seller' 'shipped - rejected by buyer' 'pending'
 'shipped - picked up' 'shipped - returning to seller'
 'shipped - out for delivery' 'shipped - lost in transit' 'shipping'
 'shipped - damaged' 'pending - waiting for pick up']

Fulfilment:
['amazon' 'merchant']

Category:
['kurta' 'set' 'western dress' 'top' 'ethnic dress' 'blouse' 'bottom'
 'saree' 'dupatta']

Sales Channel:
['amazon.in' 'non-amazon']

Ship Service Level:
['expedited' 'standard']

In [31]:
#Check the cleaned dataset
print("Final shape:", df.shape)

df.head()

Final shape: (128942, 19)

,order_id,date,status,fulfilment,sales_channel,ship_service_level,style,sku,category,size,asin,courier_status,qty,amount,ship_city,ship_state,ship_postal_code,promotion_ids,b2b
0,171-7326790-9044369,2022-03-31,shipped,amazon,amazon.in,expedited,jne3614,jne3614-kr-l,kurta,l,b098133pv7,shipped,1,453.00,arani tiruvannamalai district,tamil nadu,632317,in core free shipping 2015/04/08 23-48-5-108,False
1,171-7326790-9044369,2022-03-31,shipped,amazon,amazon.in,expedited,jne3294,jne3294-kr-l,kurta,l,b07r5wm5yr,shipped,1,353.00,arani tiruvannamalai district,tamil nadu,632317,in core free shipping 2015/04/08 23-48-5-108,False
2,171-7192082-3049169,2022-03-31,cancelled,merchant,amazon.in,standard,jne3461,jne3461-kr-l,kurta,l,b08b3ywtlk,unknown,0,360.95,arani tiruvannamalai district,tamil nadu,632317,unknown,False
3,402-9467302-4929937,2022-03-31,shipped,amazon,amazon.in,expedited,jne3405,jne3405-kr-xxxl,kurta,3xl,b081wz4t3v,shipped,1,449.00,panchkula,haryana,134116,unknown,False
4,405-1392423-9557138,2022-03-31,shipped,amazon,amazon.in,expedited,jne3068,jne3068-kr-a-l,kurta,l,b07h7d7njz,shipped,1,688.00,tirupati,andhra pradesh,517501,in core free shipping 2015/04/08 23-48-5-108,False

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 128942 entries, 0 to 128948
Data columns (total 19 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   order_id            128942 non-null  object
 1   date                128942 non-null  datetime64[ns]
 2   status              128942 non-null  object
 3   fulfilment          128942 non-null  object
 4   sales_channel       128942 non-null  object
 5   ship_service_level  128942 non-null  object
 6   style               128942 non-null  object
 7   sku                 128942 non-null  object
 8   category            128942 non-null  object
 9   size                128942 non-null  object
 10  asin                128942 non-null  object
 11  courier_status      128942 non-null  object
 12  qty                 128942 non-null  int64
 13  amount              121152 non-null  float64
 14  ship_city           128942 non-null  object
 15  ship_state          128942 non-null  object
 16  ship_postal_code    128942 non-null  string
 17  promotion_ids       128942 non-null  object
 18  b2b                 128942 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(1), int64(1), object(14), string(1)
memory usage: 18.8+ MB

In [33]:
#Final missing-value check
final_missing = pd.DataFrame({
    "missing_count": df.isnull().sum(),
    "missing_percentage": (
        df.isnull().sum() / len(df) * 100
    ).round(2)
})

final_missing = final_missing[
    final_missing["missing_count"] > 0
]

print(final_missing)

        missing_count  missing_percentage
amount           7790                6.04

In [34]:
#Final duplicate check
print(
    "Exact duplicate rows:",
    df.duplicated().sum()
)

print(
    "Unique orders:",
    df["order_id"].nunique()
)

print(
    "Total rows:",
    len(df)
)

Exact duplicate rows: 0
Unique orders: 120351
Total rows: 128942

In [35]:
#Numerical summary
df.describe()

                                date            qty         amount
count                         128942  128942.000000  121152.000000
mean   2022-05-12 11:47:38.904003072       0.904655     648.545116
min              2022-03-31 00:00:00       0.000000       0.000000
25%              2022-04-20 00:00:00       1.000000     449.000000
50%              2022-05-10 00:00:00       1.000000     605.000000
75%              2022-06-04 00:00:00       1.000000     788.000000
max              2022-06-29 00:00:00      15.000000    5584.000000
std                              NaN       0.314749     281.216488

In [36]:
#Number of unique values in each columns
unique_report = pd.DataFrame({
    "column": df.columns,
    "unique_values": [
        df[col].nunique()
        for col in df.columns
    ]
})

print(unique_report)

                column  unique_values
0             order_id         120351
1                 date             91
2               status             13
3           fulfilment              2
4        sales_channel              2
5   ship_service_level              2
6                style           1377
7                  sku           7195
8             category              9
9                 size             11
10                asin           7190
11      courier_status              4
12                 qty             10
13              amount           1410
14           ship_city           7287
15          ship_state             38
16    ship_postal_code           9459
17       promotion_ids           5788
18                 b2b              2

In [37]:
#total orders 
total_orders = df["order_id"].nunique()

print("Total Orders:", total_orders)

Total Orders: 120351

In [38]:
#total units
total_units = df["qty"].sum()

print("Total Units Sold:", total_units)

Total Units Sold: 116648

In [55]:
#total units 
total_revenue = df["amount"].sum()

print("Total Revenue: ₹", round(total_revenue, 2))

Total Revenue: ₹ 78572537.94

In [56]:
total_units = df["qty"].sum()

print("Total Units Sold:", total_units)

Total Units Sold: 116648

In [54]:
order_revenue = (
    df.groupby("order_id")["amount"]
    .sum()
)

aov = order_revenue.mean()

print("Average Order Value: ₹", round(aov, 2))

Average Order Value: ₹ 652.86

In [57]:
cancelled_orders = (
    df.loc[
        df["status"] == "cancelled",
        "order_id"
    ].nunique()
)

cancellation_rate = (
    cancelled_orders / total_orders * 100
)

print(
    "Cancellation Rate:",
    round(cancellation_rate, 2),
    "%"
)

Cancellation Rate: 14.29 %

In [53]:
category_sales = (
    df.groupby("category")["amount"]
    .sum()
    .sort_values(ascending=False)
)

print(category_sales)

category
set              39193984.67
kurta            21294599.70
western dress    11212423.69
top               5347242.30
ethnic dress       790362.66
blouse             458408.18
bottom             150667.98
saree              123933.76
dupatta               915.00
Name: amount, dtype: float64

In [52]:
print(df.columns.tolist())

['order_id', 'date', 'status', 'fulfilment', 'sales_channel', 'ship_service_level', 'style', 'sku', 'category', 'size', 'asin', 'courier_status', 'qty', 'amount', 'ship_city', 'ship_state', 'ship_postal_code', 'promotion_ids', 'b2b']

In [58]:
df.to_excel("amazon_sales_cleaned.xlsx", index=False)

In [59]:
import os

print(os.getcwd())

C:\Users\Admin